import Head from 'next/head';
import Header from '../components/Header';
import FeedbackList from '../components/FeedbackList.jsx';
import Card from '../components/shared/Card.jsx';
import FeedbackStats from '../components/FeedbackStats';
import FeedbackForm from '../components/FeedbackForm';
import { FeedbackProvider } from '../context/FeedbackContext';

export default function Home() {

  return (
    <FeedbackProvider>
      <>
        <Head>
          <title>yesweb</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <div className="container">
            <FeedbackForm  />
            <Card reverse>
              <h2>This is a Card Component</h2>
            </Card>
            <FeedbackStats />
            <FeedbackList />
          </div>
        </main>
      </>
    </FeedbackProvider>
  );
}
